import { useEffect, useRef, useState } from 'react';
import type { CSSProperties, PointerEvent } from 'react';

type IconName = 'arrow' | 'shuffle' | 'bookmark' | 'close' | 'spark' | 'check' | 'sun' | 'moon' | 'play' | 'undo' | 'download' | 'menu';
function Icon({ name, size = 20, ...props }: { name: IconName; size?: number; className?: string }) {
  const paths: Record<IconName, React.ReactNode> = {
    arrow: <><path d="M5 19 19 5M5 5h14v14" /></>,
    shuffle: <><path d="m17 3 4 4-4 4m0 2 4 4-4 4M3 7h3c5 0 7 10 12 10h3M3 17h3c2 0 3-2 5-5m3-4c1-1 3-1 4-1h3" /></>,
    bookmark: <path d="M6 4h12v17l-6-4-6 4V4Z" />,
    close: <path d="m6 6 12 12M6 18 18 6" />,
    spark: <><path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z" /></>,
    check: <path d="m5 12 4 4L19 6" />,
    sun: <><circle cx="12" cy="12" r="4" /><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5" /></>,
    moon: <path d="M20 14A8 8 0 0 1 10 4a8 8 0 1 0 10 10Z" />,
    play: <path d="m9 5 11 7-11 7V5Z" />,
    undo: <><path d="M4 10h10a6 6 0 0 1 0 12M4 10l5-5M4 10l5 5" /></>,
    download: <><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5" /></>,
    menu: <path d="M4 7h16M4 12h16M4 17h16" />,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" {...props}>{paths[name]}</svg>;
}
function Asterisk({ className = '' }: { className?: string }) { return <svg className={className} viewBox="0 0 100 100" fill="currentColor" aria-hidden="true">{Array.from({ length: 8 }, (_, i) => <rect key={i} x="44" y="3" width="12" height="94" rx="5" transform={`rotate(${i * 22.5} 50 50)`} />)}</svg>; }

type Mood = 'All the feels' | 'Feeling curious' | 'Need a breather' | 'Let’s create' | 'Surprise me';
type Discovery = { id: number; title: string; description: string; category: string; time: string; art: string; mood: Mood; action: string; content: string; kind: 'breathe' | 'draw' | 'idea' | 'challenge' };
const discoveries: Discovery[] = [
  { id: 1, title: 'Somewhere, slower.', description: 'A little escape. A whole new headspace.', category: 'A MOMENT OF CALM', time: '2 min reset', art: 'landscape', mood: 'Need a breather', action: 'Find a little stillness', content: 'You don’t need to be anywhere else right now. Unclench your jaw, let your shoulders drop, and follow the circle. Breathe in as it grows. Breathe out as it softens.', kind: 'breathe' },
  { id: 2, title: 'What if you just… made it?', description: 'No brief. No rules. Just your imagination.', category: 'THE CREATIVE CORNER', time: 'Your own pace', art: 'flower', mood: 'Let’s create', action: 'Make your first mark', content: 'A blank canvas is an invitation, not a test. Pick a color. Make a mark. See where it takes you. There’s no wrong way to do this.', kind: 'draw' },
  { id: 3, title: 'Down the rabbit hole.', description: 'Unexpected ideas for an unexpected you.', category: 'WONDER WORTH WANDERING', time: '5 min adventure', art: 'orb', mood: 'Feeling curious', action: 'Follow your curiosity', content: 'The best ideas tend to live at the intersection of two things that have never met. Here’s a little creative collision to get you started.', kind: 'idea' },
  { id: 4, title: 'Look a little closer.', description: 'Find something extraordinary in the everyday.', category: 'AN EVERYDAY EXPEDITION', time: '10 min detour', art: 'peach', mood: 'Feeling curious', action: 'Accept your little mission', content: 'Find five things around you in the same color. Arrange them into a tiny, unexpected collection. Give your collection a name that sounds like the title of a film. Your ordinary day just became an art direction exercise.', kind: 'challenge' },
  { id: 5, title: 'A softer kind of Sunday.', description: 'A deep breath, whatever day it is.', category: 'SPACE TO JUST BE', time: '2 min reset', art: 'landscape', mood: 'Need a breather', action: 'Take a softer moment', content: 'For the next little while, your only job is to breathe. Let the outside world carry on without you. Follow the circle and come back to yourself.', kind: 'breathe' },
  { id: 6, title: 'Beautifully imperfect.', description: 'Make a mess. Find a masterpiece.', category: 'PERMISSION TO EXPERIMENT', time: 'Your own pace', art: 'flower', mood: 'Let’s create', action: 'Let’s make a happy accident', content: 'Try drawing a face without lifting your finger. Or your favorite place using only three colors. Imperfection is where the interesting things happen.', kind: 'draw' },
];
const ideaPairs = [ ['a tiny bookshop', 'the moon', 'Imagine a bookshop that only opens under moonlight. What stories would it sell?'], ['a rainy afternoon', 'a time machine', 'Design a little ritual that lets you revisit your favorite rainy-day memory.'], ['a houseplant', 'a secret language', 'What if plants could leave us notes? Write the first message yours would send.'], ['a city rooftop', 'an underwater world', 'Imagine a rooftop garden inspired by a coral reef. What would grow there?'], ['your morning coffee', 'a parallel universe', 'Invent a café menu from a world where emotions are flavors. What’s your order?'] ];
const moods: { label: Mood; emoji: string }[] = [{ label: 'All the feels', emoji: '✳' }, { label: 'Feeling curious', emoji: '👀' }, { label: 'Need a breather', emoji: '☁' }, { label: 'Let’s create', emoji: '✎' }, { label: 'Surprise me', emoji: '✧' }];
const readStored = <T,>(key: string, fallback: T): T => { try { return JSON.parse(localStorage.getItem(key) || 'null') ?? fallback; } catch { return fallback; } };

function Art({ art }: { art: string }) {
  if (art === 'landscape') return <img className="landscape-img" src="https://images.pexels.com/photos/28578414/pexels-photo-28578414.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=650&w=1000" alt="Dreamlike rolling green hills beneath soft white clouds" />;
  if (art === 'flower') return <div className="flower-art"><div className="flower-shape">{Array.from({ length: 8 }, (_, i) => <span key={i} style={{ '--angle': `${i * 45}deg` } as CSSProperties} />)}<i /></div><span className="art-scribble">just play.</span><div className="mini-flower">✳</div></div>;
  if (art === 'peach') return <div className="peach-art"><Asterisk /><span>Look again.</span></div>;
  return <div className="orb-art"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orb" /><span className="orb-star">✧</span><span className="orb-caption">a different perspective.</span></div>;
}

function DrawingCanvas() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const drawing = useRef(false);
  const [color, setColor] = useState('#8053cd');
  const [width, setWidth] = useState(6);
  function position(e: PointerEvent<HTMLCanvasElement>) { const rect = e.currentTarget.getBoundingClientRect(); return [(e.clientX - rect.left) * 1000 / rect.width, (e.clientY - rect.top) * 560 / rect.height]; }
  function start(e: PointerEvent<HTMLCanvasElement>) { const ctx = canvasRef.current?.getContext('2d'); if (!ctx) return; drawing.current = true; e.currentTarget.setPointerCapture(e.pointerId); const [x, y] = position(e); ctx.beginPath(); ctx.moveTo(x, y); ctx.strokeStyle = color; ctx.lineWidth = width; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.lineTo(x + .1, y + .1); ctx.stroke(); }
  function move(e: PointerEvent<HTMLCanvasElement>) { if (!drawing.current) return; const ctx = canvasRef.current?.getContext('2d'); if (ctx) { const [x, y] = position(e); ctx.lineTo(x, y); ctx.stroke(); } }
  function download() { const source = canvasRef.current; if (!source) return; const output = document.createElement('canvas'); output.width = 1000; output.height = 560; const ctx = output.getContext('2d')!; ctx.fillStyle = '#fffdf8'; ctx.fillRect(0, 0, 1000, 560); ctx.drawImage(source, 0, 0); const a = document.createElement('a'); a.download = 'my-offscript-moment.png'; a.href = output.toDataURL(); a.click(); }
  return <div className="drawing-studio"><div className="canvas-tools"><div className="swatches">{['#8053cd', '#f08b52', '#77944a', '#242322', '#e685a1'].map(c => <button key={c} className={c === color ? 'swatch selected' : 'swatch'} style={{ background: c }} onClick={() => setColor(c)} aria-label={`Use ${c} ink`} />)}</div><label className="brush-size">Brush <input aria-label="Brush size" type="range" min="2" max="24" value={width} onChange={e => setWidth(+e.target.value)} /></label><button className="icon-button" title="Clear canvas" onClick={() => canvasRef.current?.getContext('2d')?.clearRect(0, 0, 1000, 560)}><Icon name="undo" /></button></div><canvas ref={canvasRef} width={1000} height={560} onPointerDown={start} onPointerMove={move} onPointerUp={() => drawing.current = false} onPointerCancel={() => drawing.current = false} aria-label="Your freeform drawing canvas" /><div className="canvas-bottom"><span>A little messy is a little wonderful.</span><button className="text-button" onClick={download}>Keep your creation <Icon name="download" size={17} /></button></div></div>;
}

function BreathingExercise() {
  const [running, setRunning] = useState(false);
  const [seconds, setSeconds] = useState(0);
  useEffect(() => { if (!running) return; const t = window.setInterval(() => setSeconds(s => { if (s >= 119) { setRunning(false); return 120; } return s + 1; }), 1000); return () => clearInterval(t); }, [running]);
  const label = !running ? seconds === 120 ? 'A little more you.' : 'Come as you are.' : seconds % 8 < 4 ? 'Breathe in' : 'Breathe out';
  return <div className="breathing-exercise"><div className={`breath-orbit ${running ? 'running' : ''}`}><div className="breath-circle"><Icon name="spark" size={30} /><span>{label}</span></div></div><p>{running ? `${Math.floor((120 - seconds) / 60)}:${String((120 - seconds) % 60).padStart(2, '0')} of space, just for you` : 'Two minutes. Nothing to prove.'}</p><button className="button dark" onClick={() => { if (seconds === 120) setSeconds(0); setRunning(!running); }}>{running ? 'Pause for a moment' : seconds > 0 && seconds < 120 ? 'Continue your moment' : 'Let’s take a breath'}<Icon name={running ? 'moon' : 'play'} size={18} /></button></div>;
}

export default function App() {
  const [page, setPage] = useState<'Discover' | 'Playground' | 'Collections'>('Discover');
  const [mood, setMood] = useState<Mood>('All the feels');
  const [saved, setSaved] = useState<number[]>(() => readStored('offscript-saved', []));
  const [selected, setSelected] = useState<Discovery | null>(null);
  const [profileOpen, setProfileOpen] = useState(false);
  const [name, setName] = useState(() => readStored('offscript-name', ''));
  const [draftName, setDraftName] = useState(name);
  const [theme, setTheme] = useState(() => readStored('offscript-theme', 'lilac'));
  const [toast, setToast] = useState('');
  const [idea, setIdea] = useState(0);
  const [showAll, setShowAll] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [completed, setCompleted] = useState<number[]>(() => readStored('offscript-completed', []));
  const feedRef = useRef<HTMLElement>(null);
  useEffect(() => { localStorage.setItem('offscript-saved', JSON.stringify(saved)); }, [saved]);
  useEffect(() => { localStorage.setItem('offscript-completed', JSON.stringify(completed)); }, [completed]);
  useEffect(() => { localStorage.setItem('offscript-theme', JSON.stringify(theme)); document.documentElement.dataset.theme = theme; }, [theme]);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(''), 3200); return () => clearTimeout(id); }, [toast]);
  useEffect(() => {
    if (!selected && !profileOpen) return;
    const previous = document.activeElement as HTMLElement | null;
    document.body.style.overflow = 'hidden';
    const fn = (e: KeyboardEvent) => {
      if (e.key === 'Escape') { setSelected(null); setProfileOpen(false); }
      if (e.key === 'Tab') {
        const items = document.querySelector('[role="dialog"]')?.querySelectorAll<HTMLElement>('button:not([disabled]), input, [tabindex="0"]');
        if (!items?.length) return;
        const first = items[0], last = items[items.length - 1];
        if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
        else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
      }
    };
    document.addEventListener('keydown', fn);
    return () => { document.body.style.overflow = ''; document.removeEventListener('keydown', fn); if (previous?.isConnected) previous.focus(); };
  }, [selected, profileOpen]);
  const toggleSave = (id: number) => { setSaved(s => s.includes(id) ? s.filter(x => x !== id) : [...s, id]); setToast(saved.includes(id) ? 'A little room for something new. Removed from your collection.' : 'A good thing, kept. Added to your collection.'); };
  function navigate(next: typeof page) { setPage(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function surprise() { const pool = discoveries.filter(d => d.id !== selected?.id); setSelected(pool[Math.floor(Math.random() * pool.length)]); setIdea(Math.floor(Math.random() * ideaPairs.length)); }
  function chooseMood(next: Mood) { if (next === 'Surprise me') { surprise(); return; } setMood(next); setShowAll(false); }
  const visible = page === 'Collections' ? discoveries.filter(d => saved.includes(d.id)) : (mood === 'All the feels' ? discoveries : discoveries.filter(d => d.mood === mood)).slice(0, showAll ? 6 : 3);
  function discoveryCard(d: Discovery, i: number) { return <article className={`discovery-card reveal card-${i}`} key={d.id}><div className={`card-art ${d.art}`} onClick={() => setSelected(d)} role="button" tabIndex={0} onKeyDown={e => { if (e.target === e.currentTarget && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); setSelected(d); } }} aria-label={`Explore ${d.title}`}><Art art={d.art} /><span className="card-tag">{d.category}</span><button className={`save-button ${saved.includes(d.id) ? 'is-saved' : ''}`} aria-label={saved.includes(d.id) ? `Unsave ${d.title}` : `Save ${d.title}`} onClick={e => { e.stopPropagation(); toggleSave(d.id); }}><Icon name={saved.includes(d.id) ? 'check' : 'bookmark'} size={18} /></button><span className="card-time">{d.time}</span></div><button className="card-title" onClick={() => setSelected(d)}><h3>{d.title}</h3><Icon name="arrow" size={23} /></button><p>{d.description}</p></article>; }

  return <div className="app-shell">
    <header className="site-header"><a href="#" onClick={e => { e.preventDefault(); navigate('Discover'); }} className="brand" aria-label="Offscript home"><Asterisk />offscript<span className="brand-dot">®</span></a><nav className={menuOpen ? 'main-nav mobile-open' : 'main-nav'} aria-label="Main navigation">{(['Discover', 'Playground', 'Collections'] as const).map(p => <button key={p} className={page === p ? 'nav-link active' : 'nav-link'} onClick={() => navigate(p)}>{p}{p === 'Playground' && <span className="new-dot" />}{p === 'Collections' && saved.length > 0 && <span className="collection-count">{saved.length}</span>}</button>)}</nav><div className="header-right"><span className="little-reminder"><span className="status-dot" />A GOOD DAY TO GET LOST</span><button className="profile-button" onClick={() => { setDraftName(name); setProfileOpen(true); }}>{name ? `Hey, ${name}` : 'Make it yours'}<Icon name="arrow" size={17} /></button><button className="mobile-menu icon-button" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}><Icon name={menuOpen ? 'close' : 'menu'} /></button></div></header>

    <main>
      {page === 'Discover' && <>
        <section className="hero page-width"><div className="hero-copy"><div className="eyebrow"><span className="tiny-spark">✳</span> LESS ORDINARY. MORE POSSIBILITY.</div><h1>Stay curious.<br />Make a little<br /><span className="magic">magic<span className="magic-period">.</span><svg viewBox="0 0 300 24" aria-hidden="true"><path d="M4 16C77 0 176 1 292 9M27 22C119 8 211 9 263 14" /></svg></span><span className="title-spark">✧</span></h1><p className="hero-description">A feel-good corner of the internet to explore,<br className="desktop-break" /> play, and stumble into something wonderful.</p><div className="hero-actions"><button className="button dark" onClick={() => feedRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>Find your spark <Icon name="arrow" size={19} /></button><button className="surprise-button" onClick={surprise}><Icon name="shuffle" size={19} />Or, surprise me</button></div><div className="hero-social"><div className="avatar-stack"><img src="https://i.pravatar.cc/72?img=47" alt="" /><img src="https://i.pravatar.cc/72?img=12" alt="" /><img src="https://i.pravatar.cc/72?img=49" alt="" /><span>✳</span></div><span>A little escape for <strong>curious minds.</strong></span><svg className="social-swoop" viewBox="0 0 65 35"><path d="M4 24C14 34 40 27 49 5m-11 5 12-7 7 12" /></svg></div></div>
        <div className="hero-visual"><div className="image-halo" /><div className="hero-image-wrap"><img className="hero-image" src="/images/curiosity.jpg" alt="A floating liquid chrome sculpture with playful orange and lime spheres in a lavender dreamscape" /></div><div className="curiosity-sticker"><span>LESS SCROLL</span><Asterisk /><span>MORE SOUL</span></div><svg className="hero-squiggle" viewBox="0 0 100 95" aria-hidden="true"><path d="M6 45c18-36 21 55 40 19s-2-58 7-36 22 47 24 17 3-26 17-20" /></svg><div className="floating-label"><span className="label-spark">✳</span>100% curiosity. 0% rules.</div><button className="permission-card" onClick={() => navigate('Playground')}><span>YOUR DAILY REMINDER</span><strong>You’re allowed<br />to just play.</strong><Icon name="arrow" size={20} /></button><span className="visual-caption">A SMALL STEP OUTSIDE THE ALGORITHM.</span></div></section>
        <div className="ticker" aria-hidden="true"><div><span>Good things happen offscript</span><Asterisk /><span>Follow the feeling</span><Asterisk /><span>Less perfect. More playful.</span><Asterisk /><span>Find your kind of wonder</span><Asterisk /><span>Good things happen offscript</span><Asterisk /></div></div>
        <section className="discovery-section page-width" ref={feedRef}><div className="mood-row"><span>What’s your headspace?</span><div className="mood-options">{moods.map(m => <button className={`mood-chip ${mood === m.label ? 'selected' : ''}`} key={m.label} onClick={() => chooseMood(m.label)}><span>{m.emoji}</span>{m.label}</button>)}</div><span className="no-wrong">no wrong answers <svg viewBox="0 0 50 25"><path d="M3 7c10 13 26 16 40 4m-10-3 13 1-4 11" /></svg></span></div><div className="section-heading"><div><div className="eyebrow section-eyebrow">A FEW GOOD PLACES TO START</div><h2>{mood === 'All the feels' ? 'Follow your kind of curious.' : mood === 'Need a breather' ? 'A little room to breathe.' : mood === 'Let’s create' ? 'Let your imagination out.' : 'Wonder what’s out there?'}</h2></div><button className="text-button explore-all" onClick={() => { setMood('All the feels'); setShowAll(!showAll); }}>{showAll ? 'A little less' : 'Explore everything'}<Icon name="arrow" size={18} /></button></div><div className="discovery-grid">{visible.map(discoveryCard)}</div></section>
        <section className="daily-detour page-width"><div className="detour-art"><Asterisk /><span>↝</span></div><div className="detour-copy"><div className="eyebrow">THE DAILY DETOUR</div><h2>Your routine called.<br />It could use a plot twist.</h2><p>A small, unexpected mission. A different way to see your day.</p></div><button className="button dark" onClick={() => setSelected(discoveries[3])}>Take the scenic route <Icon name="arrow" size={19} /></button><span className="detour-note">a little outside your usual ↗</span></section>
      </>}

      {page === 'Playground' && <section className="inner-page page-width"><div className="page-intro"><div className="eyebrow"><Icon name="spark" size={16} /> NOTHING TO PROVE. EVERYTHING TO PLAY WITH.</div><h1>Less thinking.<br /><em>More tinkering.</em></h1><p>Leave the rules at the door. Your imagination’s got this.</p></div><div className="playground-layout"><div className="studio-panel"><div className="studio-heading"><div><div className="eyebrow">THE NO-PRESSURE STUDIO</div><h2>Make a happy accident.</h2></div><span className="studio-badge">JUST FOR THE FUN OF IT</span></div><DrawingCanvas /></div><div className="idea-panel"><Icon name="spark" size={33} /><div className="eyebrow">THE WHAT-IF MACHINE</div><h2>A spark from<br />two strangers.</h2><p>Unexpected combinations.<br />Entirely new possibilities.</p><div className="idea-pair"><span>{ideaPairs[idea][0]}</span><b>+</b><span>{ideaPairs[idea][1]}</span></div><p className="idea-prompt">{ideaPairs[idea][2]}</p><button className="button dark" onClick={() => setIdea(i => (i + 1) % ideaPairs.length)}>Another little spark <Icon name="shuffle" size={18} /></button></div></div><button className="play-breathe" onClick={() => setSelected(discoveries[0])}><Icon name="sun" size={27} /><span>Creative pause? There’s a quiet corner just for you.</span><span>Take a breath <Icon name="arrow" size={18} /></span></button></section>}

      {page === 'Collections' && <section className="inner-page collections-page page-width"><div className="page-intro"><div className="eyebrow"><Icon name="bookmark" size={16} /> THE GOOD THINGS, KEPT CLOSE.</div><h1>Your little<br /><em>cabinet of wonder.</em></h1><p>{saved.length ? `${saved.length} little ${saved.length === 1 ? 'discovery' : 'discoveries'}, saved for a day that needs a spark.` : 'A home for the things that make you feel something.'}</p></div>{saved.length ? <div className="discovery-grid">{visible.map(discoveryCard)}</div> : <div className="empty-collection"><Asterisk /><h2>Wonderful things belong here.</h2><p>Tap the bookmark on anything that catches your curiosity.<br />We’ll keep it right here, just for you.</p><button className="button dark" onClick={() => navigate('Discover')}>Find your first favorite <Icon name="arrow" size={18} /></button></div>}<div className="collection-note"><Icon name="check" size={16} /> Your collection is saved on this device. A little space that stays yours.</div></section>}
    </main>

    <footer className="site-footer page-width"><a className="brand footer-brand" href="#" onClick={e => { e.preventDefault(); navigate('Discover'); }}><Asterisk />offscript<span className="brand-dot">®</span></a><p>For the wonderfully unfinished you.</p><span>Made for a little more wonder. <span className="footer-spark">✳</span></span><button className="back-top" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} aria-label="Back to top">↑</button></footer>

    {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><section className={`modal discovery-modal modal-${selected.kind}`} role="dialog" aria-modal="true" aria-labelledby="discovery-title" onClick={e => e.stopPropagation()}><button className="modal-close icon-button" onClick={() => setSelected(null)} aria-label="Close discovery" autoFocus><Icon name="close" /></button><div className="eyebrow">{selected.category}</div><h2 id="discovery-title">{selected.title}</h2><p className="modal-description">{selected.content}</p>{selected.kind === 'breathe' && <BreathingExercise />}{selected.kind === 'draw' && <DrawingCanvas />}{selected.kind === 'idea' && <div className="modal-idea"><div className="idea-pair"><span>{ideaPairs[idea][0]}</span><b>+</b><span>{ideaPairs[idea][1]}</span></div><p>{ideaPairs[idea][2]}</p><button className="button dark" onClick={() => setIdea(i => (i + 1) % ideaPairs.length)}>A different collision <Icon name="shuffle" size={18} /></button></div>}{selected.kind === 'challenge' && <div className="challenge-content"><div className="challenge-colors">{['#c6c0ed', '#ec9b78', '#a8b885', '#f3d476', '#e3b7cc'].map(c => <span key={c} style={{ background: c }} />)}</div><p>Notice. Collect. Reimagine.</p><button className="button dark" onClick={() => { if (!completed.includes(selected.id)) { setCompleted(c => [...c, selected.id]); setToast('A little adventure, accomplished. Look at you go!'); } }}>{completed.includes(selected.id) ? 'A little adventure, accomplished' : 'I did my daily detour'}<Icon name="check" size={18} /></button></div>}<div className="modal-footer"><button className={`text-button ${saved.includes(selected.id) ? 'saved-text' : ''}`} onClick={() => toggleSave(selected.id)}><Icon name={saved.includes(selected.id) ? 'check' : 'bookmark'} size={18} />{saved.includes(selected.id) ? 'A good thing, kept' : 'Keep this little discovery'}</button><button className="text-button" onClick={surprise}>What’s next? <Icon name="shuffle" size={17} /></button></div></section></div>}

    {profileOpen && <div className="modal-backdrop" onClick={() => setProfileOpen(false)}><section className="modal profile-modal" role="dialog" aria-modal="true" aria-labelledby="profile-title" onClick={e => e.stopPropagation()}><button className="modal-close icon-button" onClick={() => setProfileOpen(false)} aria-label="Close personalization"><Icon name="close" /></button><Asterisk className="profile-asterisk" /><div className="eyebrow">A LITTLE MORE YOU.</div><h2 id="profile-title">Make yourself at home.</h2><p className="modal-description">Your corner of the internet should feel like yours.</p><form onSubmit={e => { e.preventDefault(); const clean = draftName.trim().slice(0, 20); setName(clean); localStorage.setItem('offscript-name', JSON.stringify(clean)); setProfileOpen(false); setToast(clean ? `Welcome to your little corner, ${clean}.` : 'A fresh feeling. Make yourself at home.'); }}><label className="input-label" htmlFor="your-name">What should we call you?</label><input id="your-name" autoFocus maxLength={20} value={draftName} onChange={e => setDraftName(e.target.value)} placeholder="Your name (or your alter ego)" /><label className="input-label">Pick your atmosphere</label><div className="theme-options">{[{ id: 'lilac', name: 'Lilac daydream', color: '#e6dcf2' }, { id: 'sage', name: 'A softer sage', color: '#dae5cb' }, { id: 'peach', name: 'Peachy feeling', color: '#f4d8c5' }].map(t => <button type="button" className={theme === t.id ? 'theme-option active' : 'theme-option'} key={t.id} onClick={() => setTheme(t.id)}><span style={{ background: t.color }}>{theme === t.id && <Icon name="check" />}</span>{t.name}</button>)}</div><button type="submit" className="button dark full-width">This feels like me <Icon name="arrow" size={18} /></button><p className="privacy-note">No account. No noise. Just saved on your device.</p></form></section></div>}
    {toast && <div className="toast" role="status"><span><Icon name="check" size={17} /></span>{toast}<button aria-label="Dismiss notification" onClick={() => setToast('')}><Icon name="close" size={15} /></button></div>}
  </div>;
}
